/*
 * Copyright (c) Meta Platforms, Inc. and affiliates.
 * All rights reserved.
 *
 * Licensed under the Oculus SDK License Agreement (the "License");
 * you may not use the Oculus SDK except in compliance with the License,
 * which is provided at the time of installation or download, or which
 * otherwise accompanies this software in either electronic or hard copy form.
 *
 * You may obtain a copy of the License at
 *
 * https://developer.oculus.com/licenses/oculussdk/
 *
 * Unless required by applicable law or agreed to in writing, the Oculus SDK
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// MODIFIED GRADLE TEMPLATE FILE TO BUILD ANDROID ON SANDCASTLE
// The main change in here is the repositories from which dependencies are retrieved: a local Sandcastle maven path was added
// to point to the location in Sandcastle where the gradle dependencies are located
// THIS MIGHT NEED TO BE UPDATED WHEN UPDATING TO A NEW VERSION OF UNITY
// The template is located at Editor\Data\PlaybackEngines\AndroidPlayer\Tools\GradleTemplates\baseProjectTemplate.gradle

pluginManagement {
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/jcenter.bintray.com' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/maven.google.com' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/central/' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/gradle-plugins/' }
    }
}

include ':launcher', ':unityLibrary'
**INCLUDES**

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)
    repositories {
        **ARTIFACTORYREPOSITORY**
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/jcenter.bintray.com' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/maven.google.com' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/central/' }
        maven { url 'https://maven.thefacebook.com/nexus/content/repositories/gradle-plugins/' }
        flatDir {
            dirs "${project(':unityLibrary').projectDir}/libs"
        }
    }
}
